name: "Cargo MSFS"
description: "Run cargo-msfs from docker container"

inputs:
  token:
    required: true
    description: "GitHub token, used to access the container image"

  run:
    required: true
    description: "The command to run in the container"

runs:
  using: composite
  steps:
    - name: Pull the latest container image
      shell: bash
      run: |
        echo "${{ inputs.token }}" | docker login ghcr.io -u navigraph-bot --password-stdin
        docker pull ghcr.io/navigraph/cargo-msfs-bin:latest

    - name: Run cargo-msfs
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/navigraph/cargo-msfs-bin:latest
        options: -v ${{ github.workspace }}:/repo-content -w /repo-content
        run: ${{ inputs.run }}
